-- INSERT INTO personal (nombre, apellido_paterno, 
-- 					  apellido_materno, puesto, calle, 
-- 					  colonia, municipio, estado, 
-- 					  numero_exterior, telefono, 
-- 					  correo) 
-- VALUES ('Edgar', 'Peres', 'Estrada', 'Cajero', 'Curatame', 
-- 		'El libramiento', 'Carácuaro', 'Michoacán', '22', '1254789354', 
-- 		'edgar@gmail.com');

-- INSERT INTO personal (nombre, apellido_paterno, 
-- 					  apellido_materno, puesto, calle, 
-- 					  colonia, municipio, estado, 
-- 					  numero_exterior, telefono, 
-- 					  correo) 
-- VALUES ('Juana', 'Paredes', 'Campos', 'Cajero', 'Loma larga', 
-- 		'Arroyo seco', 'Tiquicheo', 'Michoacán', '73', '8974356789', 
-- 		'juana@gmail.com');

-- INSERT INTO personal (nombre, apellido_paterno, 
-- 					  apellido_materno, puesto, calle, 
-- 					  colonia, municipio, estado, 
-- 					  numero_exterior, telefono, 
-- 					  correo) 
-- VALUES ('Alejandro', 'Cruz', 'Gálvez', 'Cajero', 'Palestina', 
-- 		'Roma', 'Monterrey', 'Nuevo León', '66', '2456987319', 
-- 		'alejandro@gmail.com');

-- INSERT INTO personal (nombre, apellido_paterno, 
-- 					  apellido_materno, puesto, calle, 
-- 					  colonia, municipio, estado, 
-- 					  numero_exterior, telefono, 
-- 					  correo) 
-- VALUES ('Alma', 'Hinojosa', 'Obrador', 'Cajero', 'Álamos', 
-- 		'La florida', 'Monterrey', 'Nuevo León', '17', '4897356218', 
-- 		'alma@gmail.com');

-- INSERT INTO personal (nombre, apellido_paterno, 
-- 					  apellido_materno, puesto, calle, 
-- 					  colonia, municipio, estado, 
-- 					  numero_exterior, telefono, 
-- 					  correo) 
-- VALUES ('Emmanuel', 'Arana', 'Ramírez', 'Cajero', 'Primavera', 
-- 		'San Antonio', 'Cancún', 'Quintana Roo', '98', '3256987416', 
-- 		'emmanuel@gmail.com');

-- INSERT INTO personal (nombre, apellido_paterno, 
-- 					  apellido_materno, puesto, calle, 
-- 					  colonia, municipio, estado, 
-- 					  numero_exterior, telefono, 
-- 					  correo) 
-- VALUES ('Genaro', 'Perez', 'López', 'Cajero', 'San Antonio', 
-- 		'Toreo', 'Cancún', 'Quintana Roo', '56', '3218945632', 
-- 		'genaro@gmail.com');